###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

# HTTP
httpHost = "0.0.0.0"
httpPort = 7070

# Mongo
mongoHost = "mongo"
mongoPort = 27017
mongoDatabase = "mainflux"

# NATS
redisHost = "nats"
redisPort = 4222

# MQTT
mqttHost = "mainflux-mqtt"
mqttPort = 1883
