swagger: '2.0'

info:
  title: Mainflux Core API
  description: Mainflux IoT platform core service API.
  version: "0.0.1"

schemes:
  - http
  - https

produces:
  - application/json

paths:
  /status:
    get:
      summary: Service health check
      description: |
        The endpoint returns information about the service status, i.e. whether
        or not it is capable to respond to any incoming request.
      tags:
        - Status
      responses:
        200:
          description: Service is alive and able to respond to new requests.
          schema:
            $ref: '#/definitions/Status'
        500:
          description: Service cannot fulfill any further requests.
  /devices:
    post:
      summary: Provision new device
      description: |
        New devices are registered. Once the device is created,
        it is provided with an UUID (used for suthenticating device onto the system).
      tags:
        - Devices
      parameters:
        - name: name
          in: body
          schema:
            type: string
          description: Device name.
      responses:
        201:
          description: Device is created.
          schema:
            $ref: '#/definitions/Rsp'
        400:
          description: Missing or invalid username and/or password.
        409:
          description: Provided username is not unique.
        500:
          description: Server-side error occurred.
    get:
      summary: Get all devices
      description: |
        Get all devices provisioned in the system.
      tags:
        - Devices
      responses:
        201:
          description: Devices retrieved.
          schema:
            $ref: '#/definitions/Devices'
        405:
          description: Device not found.
        500:
          description: Server-side error occurred.
  /devices/{device_id}:
    put:
      summary: Update device
      description: |
        Update device by device ID. 
      tags:
        - Devices
      parameters:
        - name: device_id
          in: path
          required: true
          type: integer
          description: Device Id.
        - name: device
          in: body
          description: Account credentials.
          schema:
            $ref: '#/definitions/Device'
      responses:
        201:
          description: Device is created.
          schema:
            $ref: '#/definitions/Rsp'
        500:
          description: Server-side error occurred.
    get:
      summary: Get device
      description: |
        Get device by device ID.
      tags:
        - Devices
      parameters:
        - name: device_id
          in: path
          required: true
          type: integer
          description: Device Id.
      responses:
        201:
          description: Device retrieved.
          schema:
            $ref: '#/definitions/Device'
        500:
          description: Server-side error occurred.
  /channels:
    post:
      summary: Provision new channel
      description: |
        New channel is registered. Once the channel is created,
        it is provided with an UUID (used for identifying this channel in the system).
      tags:
        - Channels
      responses:
        201:
          description: Channel is created.
          schema:
            $ref: '#/definitions/Rsp'
        500:
          description: Server-side error occurred.
    get:
      summary: Get all channels
      description: |
        Get all provisioned channels.
      tags:
        - Channels
      parameters:
        - name: climit
          in: query
          required: false
          type: integer
          description: Channel Limit - limits the number of retrieved channels.
        - name: elimit
          in: query
          required: false
          type: integer
          description: Entry Limit - limits the nb of retrieved channel entries.
      responses:
        201:
          description: Channels retrieved.
          schema:
            $ref: '#/definitions/Channels'
        500:
          description: Server-side error occurred.
  /channels/{channel_id}:
    put:
      summary: Update channel
      description: |
        Update channel by channel ID.
      tags:
        - Channels
      parameters:
        - name: channel_id
          in: path
          required: true
          type: integer
          description: Channel Id.
        - name: entry
          in: body
          required: true
          description: SenML.
          schema:
            $ref: '#/definitions/SenML'
      responses:
        201:
          description: Channel updated.
          schema:
            $ref: '#/definitions/Rsp'
        500:
          description: Server-side error occurred.
    get:
      summary: Get the channel
      description: |
        Get the channel by channel ID.
      tags:
        - Channels
      parameters:
        - name: channel_id
          in: path
          required: true
          type: integer
          description: Channel Id.
        - name: elimit
          in: query
          required: true
          type: integer
          description: Entry Limit - limits the nb of retrieved channel entries.
      responses:
        201:
          description: Device retrieved.
          schema:
            $ref: '#/definitions/Channel'
        500:
          description: Server-side error occurred.

definitions:
  Status:
    type: object
    properties:
      status:
        type: string
        description: Status description
  Device:
    type: array
    items:
      properties:
        id:
          type: string
          description: Id description
        name:
          type: string
          description: Name description
        description:
          type: string
          description: Description description
        online:
          type: boolean
          description: Online description
        connected_at:
          type: string
          description: ConnectedAt description
        created:
          type: string
          description: Created description
        updated:
          type: string
          description: Updated description
  Devices:
    type: array
    items:
      $ref: '#/definitions/Device'
  Rsp:
    type: object
    properties:
      response:
        type: string
        description: Response description
  Channel:
    type: array
    items:
      properties:
        id:
          type: string
          description: Id description
        name:
          type: string
          description: Name description
        description:
          type: string
          description: Description description
        owner:
          type: string
          description: Owner description
        visibility:
          type: string
          description: Visibility description
        entries:
          type: array
          items:
            properties:
              test:
                type: string
                description: Visibility description
        created:
          type: string
          description: Created description
        updated:
          type: string
          description: Updated description
  Channels:
    type: array
    items:
      $ref: '#/definitions/Channel'
  SenML:
    type: array
    items:
      properties:
        bn:
          type: string
        bt:
          type: number
        bu:
          type: string
        bver:
          type: number
        l:
          type: string
        n:
          type: string
        u:
          type: string
        t:
          type: number
        ut:
          type: number
        v:
          type: number
        vs:
          type: string
        vd:
          type: string
        vb:
          type: boolean
        s:
          type: number

